### ISSUE TITLE
执行build.sh生成的rootfs.tar.xz只有17k的大小

### ISSUE THREAD

**Issue by goldendeng** [bestwu/docker-deepin#1]
- 环境
os:deepin:15.05
debootstrap: 1.0.100

- 日志
[build.sh 输出](https://github.com/bestwu/docker-deepin/files/2485721/build.log)
[debootstrap.log](https://github.com/bestwu/docker-deepin/files/2485685/debootstrap.log)

**Comment by top-bettercode** [comment]
可能是因为debootstrap运行过程有未安装成功的软件

**Comment by goldendeng** [comment]
恩，我换了个个源就可以了。
